#!/bin/sh
# This project's last: the workflow's shared tool (~/wip-workflow/tools/last), run for this repo.
here=$(cd "$(dirname "$0")/.." && pwd)
ROB_ROOT="$here" exec elixir "${WORKFLOW_HOME:-$HOME/wip-workflow}/tools/last" "$@"
